name: chaotic_progress
description: Package for displaying chaotic progress with background and/or blur.
version: 2.0.0
homepage: https://github.com/roman-stakhovskyi/chaotic_progress

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter